name: Compile Debug
on:
  workflow_dispatch:

jobs:
  build:
    name: Compile Debug
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Compile Debug
        run: ./gradlew assembleDebug --no-daemon --no-parallel --info
